[tool.briefcase]
project_name = "MosamaticDesktop"
bundle = "com.rbeesoft"
version = "1.0"
url = "https://rbeesoft.com/mosamaticdesktop"
author = "Ralph Brecheisen"
author_email = "ralph.brecheisen@gmail.com"

[tool.briefcase.license]
file = "LICENSE"

[tool.briefcase.app.mosamaticdesktop]
formal_name = "MosamaticDesktop"
description = "My first application"
long_description = "More details about the app should go here.\n"
console = true
sources = [
    "src/mosamaticdesktop",
]
test_sources = [
    "tests",
]
requires = [
    "pyside6>=6.9",
    "mosamatic-cli>=1.5.10",
    "click<8.1.8",
    "pendulum",
    "pydicom",
    "numpy",
    "pandas",
    "openpyxl",
    "pillow",
    "python-gdcm",
    "scipy",
    "torch",
    "torchvision",
    "tensorboard==2.15.2",
    "tensorboard-data-server==0.7.2",
    "tensorflow==2.15.0",
    "tensorflow-io-gcs-filesystem>=0.31",
]
test_requires = [
    "pytest",
]

[tool.briefcase.app.mosamaticdesktop.macOS]
universal_build = true
min_os_version = "12.0"
requires = [
    "std-nslog~=1.0.3",
]

[tool.briefcase.app.mosamaticdesktop.linux]
requires = []

[tool.briefcase.app.mosamaticdesktop.linux.system.debian]
system_requires = []
system_runtime_requires = [
    "libxext6",
    "libxrender1",
    "libx11-xcb1",
    "libxkbcommon-x11-0",
    "libxcb-image0",
    "libxcb-cursor0",
    "libxcb-shape0",
    "libxcb-randr0",
    "libxcb-xfixes0",
    "libxcb-sync1",
    "libxcb-icccm4",
    "libxcb-keysyms1",
    "libfontconfig1",
    "libsm6",
    "libice6",
    "libglib2.0-0",
    "libgl1",
    "libegl1",
    "libdbus-1-3",
]

[tool.briefcase.app.mosamaticdesktop.linux.system.rhel]
system_requires = []
system_runtime_requires = [
    "qt6-qtbase-gui",
]

[tool.briefcase.app.mosamaticdesktop.linux.system.suse]
system_requires = []
system_runtime_requires = [
    "libgthread-2_0-0",
    "libQt6Gui6",
]

[tool.briefcase.app.mosamaticdesktop.linux.system.arch]
system_requires = []
system_runtime_requires = [
    "qt6-base",
]

[tool.briefcase.app.mosamaticdesktop.linux.appimage]
manylinux = "manylinux_2_28"
system_requires = []
linuxdeploy_plugins = []

[tool.briefcase.app.mosamaticdesktop.linux.flatpak]
flatpak_runtime = "org.kde.Platform"
flatpak_runtime_version = "6.9"
flatpak_sdk = "org.kde.Sdk"

[tool.briefcase.app.mosamaticdesktop.windows]
requires = []

[tool.briefcase.app.mosamaticdesktop.iOS]
supported = false

[tool.briefcase.app.mosamaticdesktop.android]
supported = false

[tool.briefcase.app.mosamaticdesktop.web]
supported = false
