from PySide6.QtWidgets import QStyle
from PySide6.QtGui import QColor

from mosamaticdesktop.ui.utils import is_macos


# MAIN APPLICATION
MOSAMATICDESKTOP_WINDOW_TITLE = 'Mosamatic Desktop'
MOSAMATICDESKTOP_NAME = 'mosamaticdesktop'
MOSAMATICDESKTOP_BUNDLE_IDENTIFIER = 'com.rbeesoft'
MOSAMATICDESKTOP_WINDOW_W = 1024
MOSAMATICDESKTOP_WINDOW_H = 600
MOSAMATICDESKTOP_WINDOW_GEOMETRY_KEY = 'window/geometry'
MOSAMATICDESKTOP_WINDOW_STATE_KEY = 'window/state'
MOSAMATICDESKTOP_STATUS_READY = 'Ready'
MOSAMATICDESKTOP_DONATE_URL = 'https://rbeesoft.nl/wordpress/'
MOSAMATICDESKTOP_DONATE_BUTTON_TEXT = 'If you wish to support us, please consider a donation by clicking here!'
MOSAMATICDESKTOP_DONATE_BUTTON_STYLESHEET = 'background-color: blue; color: white; font-weight: bold;'
MOSAMATICDESKTOP_LAST_DIRECTORY_KEY = 'last_directory'
# https://www.pythonguis.com/faq/built-in-qicons-pyqt/#qt-standard-icons
MOSAMATICDESKTOP_ICON_EXIT = QStyle.SP_MessageBoxCritical
MOSAMATICDESKTOP_ICON_SETTINGS = QStyle.SP_VistaShield
MOSAMATICDESKTOP_DATA_OBJECTS_KEY = 'dataobjects'

# SPLASH SCREEN
MOSAMATICDESKTOP_SPLASH_SCREEN_TITLE = 'Mosamatic Desktop'
MOSAMATICDESKTOP_SPLASH_SCREEN_SUB_TEXT = '(This software is for research only)'
MOSAMATICDESKTOP_SPLASH_SCREEN_TITLE_STYLE_SHEET = 'color: rgb(64, 64, 64); font-weight: bold; font-size: 32pt;'
MOSAMATICDESKTOP_SPLASH_SCREEN_SUB_TEXT_STYLE_SHEET = 'color: rgb(64, 64, 64); font-style: italic; font-size: 14pt;'
MOSAMATICDESKTOP_SPLASH_SCREEN_WINDOW_W = 500
MOSAMATICDESKTOP_SPLASH_SCREEN_WINDOW_H = 300
MOSAMATICDESKTOP_SPLASH_SCREEN_START_APP_BUTTON_TEXT = 'Start app'
MOSAMATICDESKTOP_SPLASH_SCREEN_CLOSE_BUTTON_TEXT = 'Quit'
MOSAMATICDESKTOP_SPLASH_SCREEN_BACKGROUND_IMAGE = 'body-composition.jpg'
MOSAMATICDESKTOP_SPLASH_SCREEN_BACKGROUND_IMAGE_OPACITY = 0.4

# RESOURCES
MOSAMATICDESKTOP_RESOURCES_DIR = 'mosamaticdesktop/resources'
MOSAMATICDESKTOP_RESOURCES_IMAGES_DIR = 'mosamaticdesktop/resources/images'
MOSAMATICDESKTOP_RESOURCES_IMAGES_ICONS_DIR = 'mosamaticdesktop/resources/images/icons'
MOSAMATICDESKTOP_RESOURCES_ICON = 'mosamaticdesktop.icns' if is_macos() else 'mosamaticdesktop.ico'

# MENUS
MOSAMATICDESKTOP_APP_MENU_TEXT = 'Application'
MOSAMATICDESKTOP_APP_MENU_OPEN_SETTINGS_PANEL_ACTION_TEXT = 'Settings...'
MOSAMATICDESKTOP_APP_MENU_OPEN_DATA_PANEL_ACTION_TEXT = 'Data Manager...'
MOSAMATICDESKTOP_APP_MENU_EXIT_ACTION_TEXT = 'Exit'
MOSAMATICDESKTOP_DATA_MENU_TEXT = 'Data'
MOSAMATICDESKTOP_DATA_MENU_LOAD_DICOM_FILE_ACTION_TEXT = 'Load DICOM file...'
MOSAMATICDESKTOP_DATA_MENU_LOAD_MULTI_DICOM_FILE_ACTION_TEXT = 'Load multiple DICOM files...'
MOSAMATICDESKTOP_DATA_MENU_LOAD_DICOM_SERIES_ACTION_TEXT = 'Load DICOM series...'
MOSAMATICDESKTOP_DATA_MENU_LOAD_MULTI_DICOM_SERIES_ACTION_TEXT = 'Load multiple DICOM series...'
MOSAMATICDESKTOP_PIPELINES_MENU_TEXT = 'Pipelines'
MOSAMATICDESKTOP_PIPELINES_MENU_DEFAULT_PIPELINE_ACTION_TEXT = 'DefaultPipeline'

# PANELS
MOSAMATICDESKTOP_MAIN_PANEL_NAME = 'mainpanel'

MOSAMATICDESKTOP_LOG_PANEL_TITLE = 'Output log'
MOSAMATICDESKTOP_LOG_PANEL_NAME = 'logpanel'
MOSAMATICDESKTOP_LOG_PANEL_CLEAR_LOGS_BUTTON = 'Clear logs'

MOSAMATICDESKTOP_DATA_PANEL_TITLE = 'Data Manager'
MOSAMATICDESKTOP_DATA_PANEL_NAME ='datapanel'

MOSAMATICDESKTOP_SETTINGS_PANEL_TITLE = 'Settings'
MOSAMATICDESKTOP_SETTINGS_PANEL_NAME ='settingspanel'
MOSAMATICDESKTOP_SETTINGS_PANEL_NAME_COLUMN_NAME = 'NAME'
MOSAMATICDESKTOP_SETTINGS_PANEL_VALUE_COLUMN_NAME = 'VALUE'
MOSAMATICDESKTOP_SETTINGS_PANEL_CANNOT_DISPLAY_MESSAGE = 'Cannot display (binary data)'

MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_TITLE = 'Default pipeline'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_NAME = 'defaultpipelinepanel'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_IMAGE_DIR_NAME = 'Images directory'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_IMAGE_DIR_SELECT_BUTTON_TEXT = 'Select...'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_MODEL_FILES_DIR_NAME = 'Model files directory'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_MODEL_FILES_DIR_SELECT_BUTTON_TEXT = 'Select...'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_OUTPUT_DIR_NAME = 'Output directory'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_OUTPUT_DIR_SELECT_BUTTON_TEXT = 'Select...'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_TARGET_SIZE_NAME = 'Rescale target size'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_MODEL_TYPE_NAME = 'Model type'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_MODEL_TYPE_ITEM_NAMES = ['tensorflow', 'pytorch']
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_MODEL_VERSION_NAME = 'Model version'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_MODEL_VERSION_ITEM_NAMES = ['1.0', '2.2']
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_FIG_WIDTH_NAME = 'PNG figure width'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_FIG_HEIGHT_NAME = 'PNG figure height'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_FULL_SCAN_NAME = 'Full scan'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_OVERWRITE_NAME = 'Overwrite'

# DIALOGS

MOSAMATICDESKTOP_LOAD_FILE_DIALOG_FILE_PATH_LABEL_TEXT = 'File path'
MOSAMATICDESKTOP_LOAD_FILE_DIALOG_FILE_PATH_TEXT_EDIT_PLACEHOLDER_TEXT = 'Enter file path'
MOSAMATICDESKTOP_LOAD_FILE_DIALOG_OPEN_SELECT_FILE_DIALOG_BUTTON_TEXT = 'Select file...'
MOSAMATICDESKTOP_LOAD_FILE_DIALOG_OPEN_SELECT_FILE_PATH_DIALOG_WINDOW_TITLE = 'Select file'
MOSAMATICDESKTOP_LOAD_FILE_DIALOG_LOAD_BUTTON_TEXT = 'Load'

MOSAMATICDESKTOP_LOAD_DIRECTORY_DIALOG_DIRECTORY_PATH_LABEL_TEXT = 'Directory path'
MOSAMATICDESKTOP_LOAD_DIRECTORY_DIALOG_DIRECTORY_PATH_TEXT_EDIT_PLACEHOLDER_TEXT = 'Enter directory path'
MOSAMATICDESKTOP_LOAD_DIRECTORY_DIALOG_OPEN_SELECT_DIRECTORY_DIALOG_BUTTON_TEXT = 'Select directory...'
MOSAMATICDESKTOP_LOAD_DIRECTORY_DIALOG_OPEN_SELECT_DIRECTORY_PATH_DIALOG_WINDOW_TITLE = 'Select directory'
MOSAMATICDESKTOP_LOAD_DIRECTORY_DIALOG_LOAD_BUTTON_TEXT = 'Load'

MOSAMATICDESKTOP_LOAD_DICOM_FILE_DIALOG_WINDOW_TITLE = 'Load DICOM file'

MOSAMATICDESKTOP_LOAD_MULTI_DICOM_FILE_DIALOG_WINDOW_TITLE = 'Load multiple DICOM files'

MOSAMATICDESKTOP_LOAD_DICOM_SERIES_FILE_DIALOG_WINDOW_TITLE = 'Load DICOM series'

MOSAMATICDESKTOP_LOAD_MULTI_DICOM_SERIES_DIALOG_WINDOW_TITLE = 'Load multiple DICOM series'