from PySide6.QtWidgets import QStyle

from mosamaticdesktop.ui.utils import is_macos


# MAIN APPLICATION
MOSAMATICDESKTOP_WINDOW_TITLE = 'Mosamatic Desktop'
MOSAMATICDESKTOP_NAME = 'mosamaticdesktop'
MOSAMATICDESKTOP_BUNDLE_IDENTIFIER = 'com.rbeesoft'
MOSAMATICDESKTOP_WINDOW_W = 1024
MOSAMATICDESKTOP_WINDOW_H = 600
MOSAMATICDESKTOP_WINDOW_GEOMETRY_KEY = 'window/geometry'
MOSAMATICDESKTOP_WINDOW_STATE_KEY = 'window/state'
MOSAMATICDESKTOP_STATUS_READY = 'Ready'
MOSAMATICDESKTOP_DONATE_URL = 'https://rbeesoft.nl/wordpress/'
MOSAMATICDESKTOP_DONATE_BUTTON_TEXT = 'Click here if you\'d like to donate!'
MOSAMATICDESKTOP_DONATE_BUTTON_STYLESHEET = 'background-color: blue; color: white; font-weight: bold;'
MOSAMATICDESKTOP_LAST_DIRECTORY_KEY = 'mosamaticdesktop/last_directory'
# https://www.pythonguis.com/faq/built-in-qicons-pyqt/#qt-standard-icons
MOSAMATICDESKTOP_ICON_EXIT = QStyle.SP_MessageBoxCritical
MOSAMATICDESKTOP_ICON_SETTINGS = QStyle.SP_VistaShield

# RESOURCES
MOSAMATICDESKTOP_RESOURCES_DIR = 'mosamaticdesktop/resources'
MOSAMATICDESKTOP_RESOURCES_IMAGES_DIR = 'mosamaticdesktop/resources/images'
MOSAMATICDESKTOP_RESOURCES_IMAGES_ICONS_DIR = 'mosamaticdesktop/resources/images/icons'
MOSAMATICDESKTOP_RESOURCES_ICON = 'mosamaticdesktop.icns' if is_macos() else 'mosamaticdesktop.ico'

# MENUS
MOSAMATICDESKTOP_APP_MENU_TEXT = 'Application'
MOSAMATICDESKTOP_APP_MENU_OPEN_SETTINGS_ACTION_TEXT = 'Settings...'
MOSAMATICDESKTOP_APP_MENU_EXIT_ACTION_TEXT = 'Exit'
MOSAMATICDESKTOP_DATA_MENU_TEXT = 'Data'
MOSAMATICDESKTOP_DATA_MENU_LOAD_DICOM_FILE_ACTION_TEXT = 'Load DICOM file...'
MOSAMATICDESKTOP_DATA_MENU_LOAD_MULTI_DICOM_FILE_ACTION_TEXT = 'Load multiple DICOM files...'
MOSAMATICDESKTOP_DATA_MENU_LOAD_DICOM_SERIES_ACTION_TEXT = 'Load DICOM series...'

# PANELS
MOSAMATICDESKTOP_LOG_PANEL_TITLE = 'Output log'
MOSAMATICDESKTOP_LOG_PANEL_CLEAR_LOGS_BUTTON = 'Clear logs'

# DIALOGS

## -- General
MOSAMATICDESKTOP_LOAD_FILE_DIALOG_FILE_PATH_LABEL_TEXT = 'File path'
MOSAMATICDESKTOP_LOAD_FILE_DIALOG_FILE_PATH_TEXT_EDIT_PLACEHOLDER_TEXT = 'Enter file path'
MOSAMATICDESKTOP_LOAD_FILE_DIALOG_OPEN_SELECT_FILE_DIALOG_BUTTON_TEXT = 'Select file...'
MOSAMATICDESKTOP_LOAD_FILE_DIALOG_OPEN_SELECT_FILE_PATH_DIALOG_WINDOW_TITLE = 'Select file'
MOSAMATICDESKTOP_LOAD_FILE_DIALOG_LOAD_BUTTON_TEXT = 'Load'

MOSAMATICDESKTOP_LOAD_DIRECTORY_DIALOG_DIRECTORY_PATH_LABEL_TEXT = 'Directory path'
MOSAMATICDESKTOP_LOAD_DIRECTORY_DIALOG_DIRECTORY_PATH_TEXT_EDIT_PLACEHOLDER_TEXT = 'Enter directory path'
MOSAMATICDESKTOP_LOAD_DIRECTORY_DIALOG_OPEN_SELECT_DIRECTORY_DIALOG_BUTTON_TEXT = 'Select directory...'
MOSAMATICDESKTOP_LOAD_DIRECTORY_DIALOG_OPEN_SELECT_DIRECTORY_PATH_DIALOG_WINDOW_TITLE = 'Select directory'
MOSAMATICDESKTOP_LOAD_DIRECTORY_DIALOG_LOAD_BUTTON_TEXT = 'Load'

## -- Load DICOM file
MOSAMATICDESKTOP_LOAD_DICOM_FILE_DIALOG_WINDOW_TITLE = 'Load DICOM file'

## -- Load multiple DICOM files
MOSAMATICDESKTOP_LOAD_MULTI_DICOM_FILE_DIALOG_WINDOW_TITLE = 'Load multiple DICOM files'