from PySide6.QtWidgets import QStyle
from PySide6.QtGui import QColor

from mosamaticdesktop.ui.utils import is_macos


# MAIN APPLICATION

MOSAMATICDESKTOP_WINDOW_TITLE = 'Mosamatic Desktop'
MOSAMATICDESKTOP_NAME = 'mosamaticdesktop'
MOSAMATICDESKTOP_BUNDLE_IDENTIFIER = 'com.rbeesoft'
MOSAMATICDESKTOP_WINDOW_W = 1024
MOSAMATICDESKTOP_WINDOW_H = 600
MOSAMATICDESKTOP_WINDOW_GEOMETRY_KEY = 'window/geometry'
MOSAMATICDESKTOP_WINDOW_STATE_KEY = 'window/state'
MOSAMATICDESKTOP_STATUS_READY = 'Ready'
MOSAMATICDESKTOP_DONATE_URL = 'https://rbeesoft.nl/wordpress/'
MOSAMATICDESKTOP_DONATE_BUTTON_TEXT = 'If you wish to support us, please consider a donation by clicking here!'
MOSAMATICDESKTOP_DONATE_BUTTON_STYLESHEET = 'background-color: blue; color: white; font-weight: bold;'
MOSAMATICDESKTOP_LAST_DIRECTORY_KEY = 'last_directory'
# https://www.pythonguis.com/faq/built-in-qicons-pyqt/#qt-standard-icons
MOSAMATICDESKTOP_ICON_EXIT = QStyle.SP_MessageBoxCritical
MOSAMATICDESKTOP_ICON_SETTINGS = QStyle.SP_VistaShield
MOSAMATICDESKTOP_DATA_OBJECTS_KEY = 'dataobjects'

# SPLASH SCREEN

MOSAMATICDESKTOP_SPLASH_SCREEN_TITLE = 'Mosamatic Desktop'
MOSAMATICDESKTOP_SPLASH_SCREEN_SUB_TEXT = '(This software is for research only)'
MOSAMATICDESKTOP_SPLASH_SCREEN_TITLE_STYLE_SHEET = 'color: rgb(64, 64, 64); font-weight: bold; font-size: 32pt;'
MOSAMATICDESKTOP_SPLASH_SCREEN_SUB_TEXT_STYLE_SHEET = 'color: rgb(64, 64, 64); font-style: italic; font-size: 14pt;'
MOSAMATICDESKTOP_SPLASH_SCREEN_WINDOW_W = 500
MOSAMATICDESKTOP_SPLASH_SCREEN_WINDOW_H = 300
MOSAMATICDESKTOP_SPLASH_SCREEN_START_APP_BUTTON_TEXT = 'Start app'
MOSAMATICDESKTOP_SPLASH_SCREEN_CLOSE_BUTTON_TEXT = 'Quit'
MOSAMATICDESKTOP_SPLASH_SCREEN_BACKGROUND_IMAGE = 'body-composition.jpg'
MOSAMATICDESKTOP_SPLASH_SCREEN_BACKGROUND_IMAGE_OPACITY = 0.4

# RESOURCES

MOSAMATICDESKTOP_RESOURCES_DIR = 'mosamaticdesktop/resources'
MOSAMATICDESKTOP_RESOURCES_IMAGES_DIR = 'mosamaticdesktop/resources/images'
MOSAMATICDESKTOP_RESOURCES_IMAGES_ICONS_DIR = 'mosamaticdesktop/resources/images/icons'
MOSAMATICDESKTOP_RESOURCES_ICON = 'mosamaticdesktop.icns' if is_macos() else 'mosamaticdesktop.ico'

# MENUS

MOSAMATICDESKTOP_APP_MENU_TEXT = 'Application'
MOSAMATICDESKTOP_APP_MENU_OPEN_SETTINGS_PANEL_ACTION_TEXT = 'Settings...'
MOSAMATICDESKTOP_APP_MENU_OPEN_DATA_PANEL_ACTION_TEXT = 'Data Manager...'
MOSAMATICDESKTOP_APP_MENU_EXIT_ACTION_TEXT = 'Exit'
MOSAMATICDESKTOP_DATA_MENU_TEXT = 'Data'
MOSAMATICDESKTOP_DATA_MENU_LOAD_DICOM_FILE_ACTION_TEXT = 'Load DICOM file...'
MOSAMATICDESKTOP_DATA_MENU_LOAD_MULTI_DICOM_FILE_ACTION_TEXT = 'Load multiple DICOM files...'
MOSAMATICDESKTOP_DATA_MENU_LOAD_DICOM_SERIES_ACTION_TEXT = 'Load DICOM series...'
MOSAMATICDESKTOP_DATA_MENU_LOAD_MULTI_DICOM_SERIES_ACTION_TEXT = 'Load multiple DICOM series...'
MOSAMATICDESKTOP_TASKS_MENU_TEXT = 'Tasks'
MOSAMATICDESKTOP_TASKS_MENU_DECOMPRESS_DICOM_FILES_TASK_ACTION_TEXT = 'Decompress DICOM files'
MOSAMATICDESKTOP_TASKS_MENU_RESCALE_DICOM_FILES_TASK_ACTION_TEXT = 'Rescale DICOM files'
MOSAMATICDESKTOP_TASKS_MENU_SEGMENT_MUSCLE_FAT_L3_TASK_ACTION_TEXT = 'Segment muscle/fat L3'
MOSAMATICDESKTOP_TASKS_MENU_SEGMENT_MUSCLE_FAT_L3_TENSORFLOW_TASK_ACTION_TEXT = 'Segment muscle/fat L3 (TensorFlow)'
MOSAMATICDESKTOP_TASKS_MENU_CREATE_PNGS_FROM_SEGMENTATIONS_TASK_ACTION_TEXT = 'Create PNGs from segmentations'
MOSAMATICDESKTOP_TASKS_MENU_CALCULATE_SCORES_TASK_ACTION_TEXT = 'Calculate scores'
MOSAMATICDESKTOP_PIPELINES_MENU_TEXT = 'Pipelines'
MOSAMATICDESKTOP_PIPELINES_MENU_DEFAULT_PIPELINE_ACTION_TEXT = 'Default pipeline'

# PANELS

## MainPanel
MOSAMATICDESKTOP_MAIN_PANEL_NAME = 'mainpanel'
MOSAMATICDESKTOP_MAIN_PANEL_NAME_TITLE_LABEL_STYLESHEET = 'color: black; font-weight: bold; font-size: 14pt;'
## LogPanel
MOSAMATICDESKTOP_LOG_PANEL_TITLE = 'Output log'
MOSAMATICDESKTOP_LOG_PANEL_NAME = 'logpanel'
MOSAMATICDESKTOP_LOG_PANEL_CLEAR_LOGS_BUTTON = 'Clear logs'
## DataPanel
MOSAMATICDESKTOP_DATA_PANEL_TITLE = 'Data manager'
MOSAMATICDESKTOP_DATA_PANEL_NAME ='datapanel'
## SettingsPanel
MOSAMATICDESKTOP_SETTINGS_PANEL_TITLE = 'Settings'
MOSAMATICDESKTOP_SETTINGS_PANEL_NAME ='settingspanel'
MOSAMATICDESKTOP_SETTINGS_PANEL_NAME_COLUMN_NAME = 'NAME'
MOSAMATICDESKTOP_SETTINGS_PANEL_VALUE_COLUMN_NAME = 'VALUE'
MOSAMATICDESKTOP_SETTINGS_PANEL_CANNOT_DISPLAY_MESSAGE = 'Cannot display (binary data)'
## DefaultPipelinePanel
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_TITLE = 'Default pipeline'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_NAME = 'defaultpipelinepanel'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_IMAGES_DIR_NAME = 'Images directory'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_IMAGES_DIR_SELECT_BUTTON_TEXT = 'Select...'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_MODEL_FILES_DIR_NAME = 'Model files directory'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_MODEL_FILES_DIR_SELECT_BUTTON_TEXT = 'Select...'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_OUTPUT_DIR_NAME = 'Output directory'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_OUTPUT_DIR_SELECT_BUTTON_TEXT = 'Select...'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_TARGET_SIZE_NAME = 'Rescale target size'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_MODEL_TYPE_NAME = 'Model type'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_MODEL_TYPE_ITEM_NAMES = ['tensorflow', 'pytorch']
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_MODEL_VERSION_NAME = 'Model version'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_MODEL_VERSION_ITEM_NAMES = ['1.0', '2.2']
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_FIG_WIDTH_NAME = 'PNG figure width'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_FIG_HEIGHT_NAME = 'PNG figure height'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_FULL_SCAN_NAME = 'Full scan'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_OVERWRITE_NAME = 'Overwrite previous output'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_RUN_PIPELINE_BUTTON_TEXT = 'Run pipeline'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_RUN_PIPELINE_BUTTON_STYLESHEET = 'color: white; background-color: blue; font-weight: bold;'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_IMAGES_DIR_KEY = 'defaultpipelinepanel/images_dir'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_MODEL_FILES_DIR_KEY = 'defaultpipelinepanel/model_files_dir'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_OUTPUT_DIR_KEY = 'defaultpipelinepanel/output_dir'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_TARGET_SIZE_KEY = 'defaultpipelinepanel/target_size'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_MODEL_TYPE_KEY = 'defaultpipelinepanel/model_type'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_MODEL_VERSION_KEY = 'defaultpipelinepanel/model_version'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_FIG_WIDTH_KEY = 'defaultpipelinepanel/fig_width'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_FIG_HEIGHT_KEY = 'defaultpipelinepanel/fig_height'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_FULL_SCAN_KEY = 'defaultpipelinepanel/full_scan'
MOSAMATICDESKTOP_DEFAULT_PIPELINE_PANEL_OVERWRITE_KEY = 'defaultpipelinepanel/overwrite'
## DecompressDicomFilesTaskPanel
MOSAMATICDESKTOP_DECOMPRESS_DICOM_FILES_TASK_PANEL_TITLE = 'Decompress DICOM files'
MOSAMATICDESKTOP_DECOMPRESS_DICOM_FILES_TASK_PANEL_NAME = 'decompressdicomfilestaskpanel'
MOSAMATICDESKTOP_DECOMPRESS_DICOM_FILES_TASK_PANEL_IMAGE_DIR_NAME = 'Images directory'
MOSAMATICDESKTOP_DECOMPRESS_DICOM_FILES_TASK_PANEL_IMAGE_DIR_SELECT_BUTTON_TEXT = 'Select...'
MOSAMATICDESKTOP_DECOMPRESS_DICOM_FILES_TASK_PANEL_OUTPUT_DIR_NAME = 'Output directory'
MOSAMATICDESKTOP_DECOMPRESS_DICOM_FILES_TASK_PANEL_OUTPUT_DIR_SELECT_BUTTON_TEXT = 'Select...'
MOSAMATICDESKTOP_DECOMPRESS_DICOM_FILES_TASK_PANEL_OVERWRITE_NAME = 'Overwrite previous output'
MOSAMATICDESKTOP_DECOMPRESS_DICOM_FILES_TASK_PANEL_RUN_TASK_BUTTON_TEXT = 'Run task'
MOSAMATICDESKTOP_DECOMPRESS_DICOM_FILES_TASK_PANEL_RUN_TASK_BUTTON_STYLESHEET = 'color: white; background-color: blue; font-weight: bold;'
## RescaleDicomFilesTaskPanel
MOSAMATICDESKTOP_RESCALE_DICOM_FILES_TASK_PANEL_TITLE = 'Rescale DICOM files'
MOSAMATICDESKTOP_RESCALE_DICOM_FILES_TASK_PANEL_NAME = 'rescaledicomfilestaskpanel'
MOSAMATICDESKTOP_RESCALE_DICOM_FILES_TASK_PANEL_IMAGE_DIR_NAME = 'Images directory'
MOSAMATICDESKTOP_RESCALE_DICOM_FILES_TASK_PANEL_IMAGE_DIR_SELECT_BUTTON_TEXT = 'Select...'
MOSAMATICDESKTOP_RESCALE_DICOM_FILES_TASK_PANEL_OUTPUT_DIR_NAME = 'Output directory'
MOSAMATICDESKTOP_RESCALE_DICOM_FILES_TASK_PANEL_OUTPUT_DIR_SELECT_BUTTON_TEXT = 'Select...'
MOSAMATICDESKTOP_RESCALE_DICOM_FILES_TASK_PANEL_TARGET_SIZE_NAME = 'Rescale target size'
MOSAMATICDESKTOP_RESCALE_DICOM_FILES_TASK_PANEL_OVERWRITE_NAME = 'Overwrite previous output'
MOSAMATICDESKTOP_RESCALE_DICOM_FILES_TASK_PANEL_RUN_TASK_BUTTON_TEXT = 'Run task'
MOSAMATICDESKTOP_RESCALE_DICOM_FILES_TASK_PANEL_RUN_TASK_BUTTON_STYLESHEET = 'color: white; background-color: blue; font-weight: bold;'

# DIALOGS

MOSAMATICDESKTOP_LOAD_FILE_DIALOG_FILE_PATH_LABEL_TEXT = 'File path'
MOSAMATICDESKTOP_LOAD_FILE_DIALOG_FILE_PATH_TEXT_EDIT_PLACEHOLDER_TEXT = 'Enter file path'
MOSAMATICDESKTOP_LOAD_FILE_DIALOG_OPEN_SELECT_FILE_DIALOG_BUTTON_TEXT = 'Select file...'
MOSAMATICDESKTOP_LOAD_FILE_DIALOG_OPEN_SELECT_FILE_PATH_DIALOG_WINDOW_TITLE = 'Select file'
MOSAMATICDESKTOP_LOAD_FILE_DIALOG_LOAD_BUTTON_TEXT = 'Load'
MOSAMATICDESKTOP_LOAD_DIRECTORY_DIALOG_DIRECTORY_PATH_LABEL_TEXT = 'Directory path'
MOSAMATICDESKTOP_LOAD_DIRECTORY_DIALOG_DIRECTORY_PATH_TEXT_EDIT_PLACEHOLDER_TEXT = 'Enter directory path'
MOSAMATICDESKTOP_LOAD_DIRECTORY_DIALOG_OPEN_SELECT_DIRECTORY_DIALOG_BUTTON_TEXT = 'Select directory...'
MOSAMATICDESKTOP_LOAD_DIRECTORY_DIALOG_OPEN_SELECT_DIRECTORY_PATH_DIALOG_WINDOW_TITLE = 'Select directory'
MOSAMATICDESKTOP_LOAD_DIRECTORY_DIALOG_LOAD_BUTTON_TEXT = 'Load'
MOSAMATICDESKTOP_LOAD_DICOM_FILE_DIALOG_WINDOW_TITLE = 'Load DICOM file'
MOSAMATICDESKTOP_LOAD_MULTI_DICOM_FILE_DIALOG_WINDOW_TITLE = 'Load multiple DICOM files'
MOSAMATICDESKTOP_LOAD_DICOM_SERIES_FILE_DIALOG_WINDOW_TITLE = 'Load DICOM series'
MOSAMATICDESKTOP_LOAD_MULTI_DICOM_SERIES_DIALOG_WINDOW_TITLE = 'Load multiple DICOM series'